version: "3.8"

services:
  db:
    platform: linux/x86_64
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: user
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_PASSWORD: pass
      MARIADB_DATABASE: airbag-db
    ports:
      - "3306:3306"
    expose:
      - '3306'


  api_airbag:
    build:
      dockerfile: "./docker/Dockerfile"
      context: .
    environment:
      NODE_ENV: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app